const glob = require('glob');
const fs = require('fs');

const files = glob.sync('../lib/zones/**/*.ics');
const zones = {};

for (const zone of files) {
  const name = zone.replace('../lib/zones/', '').replace('.ics', '');

  zones[name] = `${name}.ics`;

  if (name.match(/^Etc\/*/)) {
    const match = name.match(/^Etc\/(.*)/);
    zones[match[1]] = zones[name];
  }

  if (name.includes('_')) {
    zones[name.replace('_', ' ')] = zones[name];
  }
}

zones['Dateline Standard Time'] = zones['GMT-12'];
zones['Samoa Standard Time'] = zones['GMT-11'];
zones['Hawaiian Standard Time'] = zones['GMT-10'];
zones['Alaskan Standard Time'] = zones['GMT-9'];
zones['Pacific Standard Time'] = zones['GMT-8'];
zones['Mountain Standard Time'] = zones['GMT-7'];
zones['Mexico Standard Time 2'] = zones['GMT-7'];
zones['US Mountain Standard Time'] = zones['GMT-7'];
zones['Central Standard Time'] = zones['GMT-6'];
zones['Canada Central Standard Time'] = zones['GMT-6'];
zones['Mexico Standard Time'] = zones['GMT-6'];
zones['Central America Standard Time'] = zones['GMT-6'];
zones['Eastern Standard Time'] = zones['GMT-5'];
zones['US Eastern Standard Time'] = zones['GMT-5'];
zones['SA Pacific Standard Time'] = zones['GMT-5'];
zones['Atlantic Standard Time'] = zones['GMT-4'];
zones['SA Western Standard Time'] = zones['GMT-4'];
zones['Pacific SA Standard Time'] = zones['GMT-4'];
zones['E South America Standard Time'] = zones['GMT-3'];
zones['SA Eastern Standard Time'] = zones['GMT-3'];
zones['Greenland Standard Time'] = zones['GMT-3'];
zones['Mid-Atlantic Standard Time'] = zones['GMT-2'];
zones['Azores Standard Time'] = zones['GMT-1'];
zones['Cape Verde Standard Time'] = zones['GMT-1'];
zones['GMT Standard Time'] = zones.GMT;
zones['Greenwich Standard Time'] = zones.Greenwich;
zones['Central Europe Standard Time'] = zones['GMT+1'];
zones['Central European Standard Time'] = zones['GMT+1'];
zones['Romance Standard Time'] = zones['GMT+1'];
zones['W Europe Standard Time'] = zones['GMT+1'];
zones['W Central Africa Standard Time'] = zones['GMT+1'];
zones['E Europe Standard Time'] = zones['GMT+2'];
zones['Egypt Standard Time'] = zones['GMT+2'];
zones['FLE Standard Time'] = zones['GMT+2'];
zones['GTB Standard Time'] = zones['GMT+2'];
zones['Israel Standard Time'] = zones['GMT+2'];
zones['South Africa Standard Time'] = zones['GMT+2'];
zones['Russian Standard Time'] = zones['GMT+3'];
zones['Arab Standard Time'] = zones['GMT+3'];
zones['E Africa Standard Time'] = zones['GMT+3'];
zones['Arabic Standard Time'] = zones['GMT+3'];
zones['Iran Standard Time'] = zones['GMT+4'];
zones['Arabian Standard Time'] = zones['GMT+4'];
zones['Caucasus Standard Time'] = zones['GMT+4'];
zones['Ekaterinburg Standard Time'] = zones['GMT+5'];
zones['West Asia Standard Time'] = zones['GMT+5'];
zones['Central Asia Standard Time'] = zones['GMT+6'];
zones['Sri Lanka Standard Time'] = zones['GMT+6'];
zones['N Central Asia Standard Time'] = zones['GMT+6'];
zones['Myanmar Standard Time'] = zones['Myanmar Time'];
zones['SE Asia Standard Time'] = zones['GMT+7'];
zones['North Asia Standard Time'] = zones['GMT+7'];
zones['China Standard Time'] = zones['GMT+8'];
zones['Singapore Standard Time'] = zones['GMT+8'];
zones['Taipei Standard Time'] = zones['GMT+8'];
zones['W Australia Standard Time'] = zones['GMT+8'];
zones['North Asia East Standard Time'] = zones['GMT+8'];
zones['Korea Standard Time'] = zones['GMT+9'];
zones['Tokyo Standard Time'] = zones['GMT+9'];
zones['Yakutsk Standard Time'] = zones['GMT+9'];
zones['AUS Central Standard Time'] = zones['Australian Central Standard Time'];
zones['Cen Australia Standard Time'] = zones['Australian Central Standard Time'];
zones['AUS Eastern Standard Time'] = zones['GMT+10'];
zones['E Australia Standard Time'] = zones['GMT+10'];
zones['Tasmania Standard Time'] = zones['GMT+10'];
zones['Vladivostok Standard Time'] = zones['GMT+10'];
zones['West Pacific Standard Time'] = zones['GMT+10'];
zones['Central Pacific Standard Time'] = zones['GMT+11'];
zones['Fiji Islands Standard Time'] = zones['GMT+12'];
zones['New Zealand Standard Time'] = zones['GMT+12'];
zones['Tonga Standard Time'] = zones['GMT+13'];

zones['Asia/Calcutta'] = zones['Asia/Kolkata'];
zones['Asia/Katmandu'] = zones['Nepal Time'];
zones['Asia/Rangoon'] = zones['Asia/Yangon'];
zones['America/Buenos Aires'] = zones['America/Argentina/Buenos Aires'];
zones['Canada/Atlantic'] = zones['America/Aruba'];
zones['Canada/Newfoundland'] = zones['Newfoundland Standard Time'];
zones['Canada/Saskatchewan'] = zones[''];
zones['US/Eastern'] = zones['America/New York'];
zones['US/Central'] = zones['America/Chicago'];
zones['US/Mountain'] = zones['America/Denver'];
zones['US/Pacific'] = zones['America/Los Angeles'];
zones['US/Arizona'] = zones['America/Phoenix'];
zones['US/East-Indiana'] = zones['America/Halifax'];
zones.ET = zones['America/New York'];
zones.CT = zones['America/Chicago'];
zones.MT = zones['America/Denver'];
zones.PT = zones['America/Los Angeles'];
zones.AK = zones['America/Anchorage'];
zones.HAST = zones['Pacific/Honolulu'];
zones.MST = zones['America/Phoenix'];
zones.AST = zones['America/Aruba'];
zones.MOST = zones['Africa/Casablanca'];
zones.GST = zones['Africa/Casablanca'];
zones.WET = zones['Europe/Amsterdam'];
zones.CET = zones['Europe/Belgrade'];
zones.RST = zones['Europe/Copenhagen'];
zones.CEST = zones['Europe/Sarajevo'];
zones.ECT = zones['Africa/Douala'];
zones.JST = zones['Europe/Bucharest'];
zones.GTBST = zones['Europe/Bucharest'];
zones.MEST = zones['Africa/Cairo'];
zones.EGST = zones['Africa/Cairo'];
zones.SST = zones['Africa/Cairo'];
zones.SAST = zones['Africa/Harare'];
zones.EET = zones['Europe/Helsinki'];
zones.ISST = zones['Asia/Jerusalem'];
zones.EEST = zones['Asia/Jerusalem'];
zones.NMST = zones['Asia/Jerusalem'];
zones.ARST = zones['Asia/Baghdad'];
zones.ABST = zones['Asia/Kuwait'];
zones.MSK = zones['Europe/Moscow'];
zones.EAT = zones['Asia/Kuwait'];
zones.IRST = zones['Asia/Tehran'];
zones.ARBST = zones['Asia/Muscat'];
zones.AZT = zones['Asia/Baku'];
zones.MUT = zones['Asia/Baku'];
zones.GET = zones['Asia/Baku'];
zones.AMT = zones['Asia/Baku'];
zones.AFT = zones['Asia/Baku'];
zones.YEKT = zones['Asia/Yekaterinburg'];
zones.PKT = zones['Asia/Karachi'];
zones.WAST = zones['Asia/Yekaterinburg'];
zones.IST = zones['Asia/Calcutta'];
zones.SLT = zones['Asia/Calcutta'];
zones.NPT = zones['Asia/Katmandu'];
zones.BTT = zones['Asia/Dhaka'];
zones.BST = zones['Asia/Dhaka'];
zones.NCAST = zones['Asia/Dhaka'];
zones.MYST = zones['Asia/Rangoon'];
zones.THA = zones['Asia/Rangoon'];
zones.KRAT = zones['Asia/Rangoon'];
zones.IRKT = zones['Asia/Irkutsk'];
zones.SNST = zones['Asia/Taipei'];
zones.AWST = zones['Australia/Perth'];
zones.TIST = zones['Asia/Taipei'];
zones.UST = zones['Asia/Taipei'];
zones.TST = zones['Asia/Tokyo'];
zones.KST = zones['Asia/Seoul'];
zones.YAKT = zones['Asia/Yakutsk'];
zones.CAUST = zones['Australia/Adelaide'];
zones.ACST = zones['Australia/Darwin'];
zones.EAST = zones['Australia/Brisbane'];
zones.AEST = zones['Australia/Sydney'];
zones.WPST = zones['Pacific/Guam'];
zones.TAST = zones['Australia/Hobart'];
zones.VLAT = zones['Asia/Vladivostok'];
zones.SBT = zones['Pacific/Guadalcanal'];
zones.NZST = zones['Pacific/Auckland'];
zones.UTC12 = zones['Etc/GMT-12'];
zones.FJT = zones['Pacific/Fiji'];
zones.PETT = zones['Etc/GMT+12'];
zones.PHOT = zones['Pacific/Tongatapu'];
zones.AZOST = zones['Atlantic/Azores'];
zones.CVT = zones['Atlantic/Cape Verde'];
zones.ESAST = zones['America/Sao_Paulo'];
zones.ART = zones['America/Buenos Aires'];
zones.SAEST = zones['SA Eastern Standard Time'];
zones.GNST = zones['America/Godthab'];
zones.MVST = zones['America/Montevideo'];
zones.NST = zones['Canada/Newfoundland'];
zones.PRST = zones['America/Aruba'];
zones.CBST = zones['America/Aruba'];
zones.SAWST = zones['America/Santiago'];
zones.PSAST = zones['America/Santiago'];
zones.VST = zones['America/Caracas'];
zones.SAPST = zones['America/Bogota'];
zones.EST = zones['America/Halifax'];
zones.CAST = zones['America/Mexico_City'];
zones.CST = zones['America/Mexico_City'];
zones.CCST = zones['Canada/Saskatchewan'];
zones.MSTM = zones['America/Mazatlan'];
zones.PST = zones['America/Los Angeles'];
zones.SMST = zones['Pacific/Midway'];
zones.BIT = zones['Etc/GMT+12'];

fs.writeFileSync('../lib/zones.js', 'module.exports = {\n');

// eslint-disable-next-line guard-for-in
for (const index in zones) {
  fs.writeFileSync('../lib/zones.js', `  '${index}': '${zones[index]}',\n`, {flag: 'a'});
}

fs.writeFileSync('../lib/zones.js', '};\n', {flag: 'a'});
