module.exports = {
  'Africa/Abidjan': 'Africa/Abidjan.ics',
  'Africa/Accra': 'Africa/Accra.ics',
  'Africa/Addis_Ababa': 'Africa/Addis_Ababa.ics',
  'Africa/Addis Ababa': 'Africa/Addis_Ababa.ics',
  'Africa/Algiers': 'Africa/Algiers.ics',
  'Africa/Asmara': 'Africa/Asmara.ics',
  'Africa/Bamako': 'Africa/Bamako.ics',
  'Africa/Bangui': 'Africa/Bangui.ics',
  'Africa/Banjul': 'Africa/Banjul.ics',
  'Africa/Bissau': 'Africa/Bissau.ics',
  'Africa/Blantyre': 'Africa/Blantyre.ics',
  'Africa/Brazzaville': 'Africa/Brazzaville.ics',
  'Africa/Bujumbura': 'Africa/Bujumbura.ics',
  'Africa/Cairo': 'Africa/Cairo.ics',
  'Africa/Casablanca': 'Africa/Casablanca.ics',
  'Africa/Ceuta': 'Africa/Ceuta.ics',
  'Africa/Conakry': 'Africa/Conakry.ics',
  'Africa/Dakar': 'Africa/Dakar.ics',
  'Africa/Dar_es_Salaam': 'Africa/Dar_es_Salaam.ics',
  'Africa/Dar es_Salaam': 'Africa/Dar_es_Salaam.ics',
  'Africa/Djibouti': 'Africa/Djibouti.ics',
  'Africa/Douala': 'Africa/Douala.ics',
  'Africa/El_Aaiun': 'Africa/El_Aaiun.ics',
  'Africa/El Aaiun': 'Africa/El_Aaiun.ics',
  'Africa/Freetown': 'Africa/Freetown.ics',
  'Africa/Gaborone': 'Africa/Gaborone.ics',
  'Africa/Harare': 'Africa/Harare.ics',
  'Africa/Johannesburg': 'Africa/Johannesburg.ics',
  'Africa/Juba': 'Africa/Juba.ics',
  'Africa/Kampala': 'Africa/Kampala.ics',
  'Africa/Khartoum': 'Africa/Khartoum.ics',
  'Africa/Kigali': 'Africa/Kigali.ics',
  'Africa/Kinshasa': 'Africa/Kinshasa.ics',
  'Africa/Lagos': 'Africa/Lagos.ics',
  'Africa/Libreville': 'Africa/Libreville.ics',
  'Africa/Lome': 'Africa/Lome.ics',
  'Africa/Luanda': 'Africa/Luanda.ics',
  'Africa/Lubumbashi': 'Africa/Lubumbashi.ics',
  'Africa/Lusaka': 'Africa/Lusaka.ics',
  'Africa/Malabo': 'Africa/Malabo.ics',
  'Africa/Maputo': 'Africa/Maputo.ics',
  'Africa/Maseru': 'Africa/Maseru.ics',
  'Africa/Mbabane': 'Africa/Mbabane.ics',
  'Africa/Mogadishu': 'Africa/Mogadishu.ics',
  'Africa/Monrovia': 'Africa/Monrovia.ics',
  'Africa/Nairobi': 'Africa/Nairobi.ics',
  'Africa/Ndjamena': 'Africa/Ndjamena.ics',
  'Africa/Niamey': 'Africa/Niamey.ics',
  'Africa/Nouakchott': 'Africa/Nouakchott.ics',
  'Africa/Ouagadougou': 'Africa/Ouagadougou.ics',
  'Africa/Porto-Novo': 'Africa/Porto-Novo.ics',
  'Africa/Sao_Tome': 'Africa/Sao_Tome.ics',
  'Africa/Sao Tome': 'Africa/Sao_Tome.ics',
  'Africa/Tripoli': 'Africa/Tripoli.ics',
  'Africa/Tunis': 'Africa/Tunis.ics',
  'Africa/Windhoek': 'Africa/Windhoek.ics',
  'America/Adak': 'America/Adak.ics',
  'America/Anchorage': 'America/Anchorage.ics',
  'America/Anguilla': 'America/Anguilla.ics',
  'America/Antigua': 'America/Antigua.ics',
  'America/Araguaina': 'America/Araguaina.ics',
  'America/Argentina/Buenos_Aires': 'America/Argentina/Buenos_Aires.ics',
  'America/Argentina/Buenos Aires': 'America/Argentina/Buenos_Aires.ics',
  'America/Argentina/Catamarca': 'America/Argentina/Catamarca.ics',
  'America/Argentina/Cordoba': 'America/Argentina/Cordoba.ics',
  'America/Argentina/Jujuy': 'America/Argentina/Jujuy.ics',
  'America/Argentina/La_Rioja': 'America/Argentina/La_Rioja.ics',
  'America/Argentina/La Rioja': 'America/Argentina/La_Rioja.ics',
  'America/Argentina/Mendoza': 'America/Argentina/Mendoza.ics',
  'America/Argentina/Rio_Gallegos': 'America/Argentina/Rio_Gallegos.ics',
  'America/Argentina/Rio Gallegos': 'America/Argentina/Rio_Gallegos.ics',
  'America/Argentina/Salta': 'America/Argentina/Salta.ics',
  'America/Argentina/San_Juan': 'America/Argentina/San_Juan.ics',
  'America/Argentina/San Juan': 'America/Argentina/San_Juan.ics',
  'America/Argentina/San_Luis': 'America/Argentina/San_Luis.ics',
  'America/Argentina/San Luis': 'America/Argentina/San_Luis.ics',
  'America/Argentina/Tucuman': 'America/Argentina/Tucuman.ics',
  'America/Argentina/Ushuaia': 'America/Argentina/Ushuaia.ics',
  'America/Aruba': 'America/Aruba.ics',
  'America/Asuncion': 'America/Asuncion.ics',
  'America/Atikokan': 'America/Atikokan.ics',
  'America/Bahia_Banderas': 'America/Bahia_Banderas.ics',
  'America/Bahia Banderas': 'America/Bahia_Banderas.ics',
  'America/Bahia': 'America/Bahia.ics',
  'America/Barbados': 'America/Barbados.ics',
  'America/Belem': 'America/Belem.ics',
  'America/Belize': 'America/Belize.ics',
  'America/Blanc-Sablon': 'America/Blanc-Sablon.ics',
  'America/Boa_Vista': 'America/Boa_Vista.ics',
  'America/Boa Vista': 'America/Boa_Vista.ics',
  'America/Bogota': 'America/Bogota.ics',
  'America/Boise': 'America/Boise.ics',
  'America/Cambridge_Bay': 'America/Cambridge_Bay.ics',
  'America/Cambridge Bay': 'America/Cambridge_Bay.ics',
  'America/Campo_Grande': 'America/Campo_Grande.ics',
  'America/Campo Grande': 'America/Campo_Grande.ics',
  'America/Cancun': 'America/Cancun.ics',
  'America/Caracas': 'America/Caracas.ics',
  'America/Cayenne': 'America/Cayenne.ics',
  'America/Cayman': 'America/Cayman.ics',
  'America/Chicago': 'America/Chicago.ics',
  'America/Chihuahua': 'America/Chihuahua.ics',
  'America/Costa_Rica': 'America/Costa_Rica.ics',
  'America/Costa Rica': 'America/Costa_Rica.ics',
  'America/Creston': 'America/Creston.ics',
  'America/Cuiaba': 'America/Cuiaba.ics',
  'America/Curacao': 'America/Curacao.ics',
  'America/Danmarkshavn': 'America/Danmarkshavn.ics',
  'America/Dawson_Creek': 'America/Dawson_Creek.ics',
  'America/Dawson Creek': 'America/Dawson_Creek.ics',
  'America/Dawson': 'America/Dawson.ics',
  'America/Denver': 'America/Denver.ics',
  'America/Detroit': 'America/Detroit.ics',
  'America/Dominica': 'America/Dominica.ics',
  'America/Edmonton': 'America/Edmonton.ics',
  'America/Eirunepe': 'America/Eirunepe.ics',
  'America/El_Salvador': 'America/El_Salvador.ics',
  'America/El Salvador': 'America/El_Salvador.ics',
  'America/Fort_Nelson': 'America/Fort_Nelson.ics',
  'America/Fort Nelson': 'America/Fort_Nelson.ics',
  'America/Fortaleza': 'America/Fortaleza.ics',
  'America/Glace_Bay': 'America/Glace_Bay.ics',
  'America/Glace Bay': 'America/Glace_Bay.ics',
  'America/Godthab': 'America/Godthab.ics',
  'America/Goose_Bay': 'America/Goose_Bay.ics',
  'America/Goose Bay': 'America/Goose_Bay.ics',
  'America/Grand_Turk': 'America/Grand_Turk.ics',
  'America/Grand Turk': 'America/Grand_Turk.ics',
  'America/Grenada': 'America/Grenada.ics',
  'America/Guadeloupe': 'America/Guadeloupe.ics',
  'America/Guatemala': 'America/Guatemala.ics',
  'America/Guayaquil': 'America/Guayaquil.ics',
  'America/Guyana': 'America/Guyana.ics',
  'America/Halifax': 'America/Halifax.ics',
  'America/Havana': 'America/Havana.ics',
  'America/Hermosillo': 'America/Hermosillo.ics',
  'America/Indiana/Indianapolis': 'America/Indiana/Indianapolis.ics',
  'America/Indiana/Knox': 'America/Indiana/Knox.ics',
  'America/Indiana/Marengo': 'America/Indiana/Marengo.ics',
  'America/Indiana/Petersburg': 'America/Indiana/Petersburg.ics',
  'America/Indiana/Tell_City': 'America/Indiana/Tell_City.ics',
  'America/Indiana/Tell City': 'America/Indiana/Tell_City.ics',
  'America/Indiana/Vevay': 'America/Indiana/Vevay.ics',
  'America/Indiana/Vincennes': 'America/Indiana/Vincennes.ics',
  'America/Indiana/Winamac': 'America/Indiana/Winamac.ics',
  'America/Inuvik': 'America/Inuvik.ics',
  'America/Iqaluit': 'America/Iqaluit.ics',
  'America/Jamaica': 'America/Jamaica.ics',
  'America/Juneau': 'America/Juneau.ics',
  'America/Kentucky/Louisville': 'America/Kentucky/Louisville.ics',
  'America/Kentucky/Monticello': 'America/Kentucky/Monticello.ics',
  'America/Kralendijk': 'America/Kralendijk.ics',
  'America/La_Paz': 'America/La_Paz.ics',
  'America/La Paz': 'America/La_Paz.ics',
  'America/Lima': 'America/Lima.ics',
  'America/Los_Angeles': 'America/Los_Angeles.ics',
  'America/Los Angeles': 'America/Los_Angeles.ics',
  'America/Lower_Princes': 'America/Lower_Princes.ics',
  'America/Lower Princes': 'America/Lower_Princes.ics',
  'America/Maceio': 'America/Maceio.ics',
  'America/Managua': 'America/Managua.ics',
  'America/Manaus': 'America/Manaus.ics',
  'America/Marigot': 'America/Marigot.ics',
  'America/Martinique': 'America/Martinique.ics',
  'America/Matamoros': 'America/Matamoros.ics',
  'America/Mazatlan': 'America/Mazatlan.ics',
  'America/Menominee': 'America/Menominee.ics',
  'America/Merida': 'America/Merida.ics',
  'America/Metlakatla': 'America/Metlakatla.ics',
  'America/Mexico_City': 'America/Mexico_City.ics',
  'America/Mexico City': 'America/Mexico_City.ics',
  'America/Miquelon': 'America/Miquelon.ics',
  'America/Moncton': 'America/Moncton.ics',
  'America/Monterrey': 'America/Monterrey.ics',
  'America/Montevideo': 'America/Montevideo.ics',
  'America/Montserrat': 'America/Montserrat.ics',
  'America/Nassau': 'America/Nassau.ics',
  'America/New_York': 'America/New_York.ics',
  'America/New York': 'America/New_York.ics',
  'America/Nipigon': 'America/Nipigon.ics',
  'America/Nome': 'America/Nome.ics',
  'America/Noronha': 'America/Noronha.ics',
  'America/North_Dakota/Beulah': 'America/North_Dakota/Beulah.ics',
  'America/North Dakota/Beulah': 'America/North_Dakota/Beulah.ics',
  'America/North_Dakota/Center': 'America/North_Dakota/Center.ics',
  'America/North Dakota/Center': 'America/North_Dakota/Center.ics',
  'America/North_Dakota/New_Salem': 'America/North_Dakota/New_Salem.ics',
  'America/North Dakota/New_Salem': 'America/North_Dakota/New_Salem.ics',
  'America/Ojinaga': 'America/Ojinaga.ics',
  'America/Panama': 'America/Panama.ics',
  'America/Pangnirtung': 'America/Pangnirtung.ics',
  'America/Paramaribo': 'America/Paramaribo.ics',
  'America/Phoenix': 'America/Phoenix.ics',
  'America/Port_of_Spain': 'America/Port_of_Spain.ics',
  'America/Port of_Spain': 'America/Port_of_Spain.ics',
  'America/Port-au-Prince': 'America/Port-au-Prince.ics',
  'America/Porto_Velho': 'America/Porto_Velho.ics',
  'America/Porto Velho': 'America/Porto_Velho.ics',
  'America/Puerto_Rico': 'America/Puerto_Rico.ics',
  'America/Puerto Rico': 'America/Puerto_Rico.ics',
  'America/Punta_Arenas': 'America/Punta_Arenas.ics',
  'America/Punta Arenas': 'America/Punta_Arenas.ics',
  'America/Rainy_River': 'America/Rainy_River.ics',
  'America/Rainy River': 'America/Rainy_River.ics',
  'America/Rankin_Inlet': 'America/Rankin_Inlet.ics',
  'America/Rankin Inlet': 'America/Rankin_Inlet.ics',
  'America/Recife': 'America/Recife.ics',
  'America/Regina': 'America/Regina.ics',
  'America/Resolute': 'America/Resolute.ics',
  'America/Rio_Branco': 'America/Rio_Branco.ics',
  'America/Rio Branco': 'America/Rio_Branco.ics',
  'America/Santarem': 'America/Santarem.ics',
  'America/Santiago': 'America/Santiago.ics',
  'America/Santo_Domingo': 'America/Santo_Domingo.ics',
  'America/Santo Domingo': 'America/Santo_Domingo.ics',
  'America/Sao_Paulo': 'America/Sao_Paulo.ics',
  'America/Sao Paulo': 'America/Sao_Paulo.ics',
  'America/Scoresbysund': 'America/Scoresbysund.ics',
  'America/Sitka': 'America/Sitka.ics',
  'America/St_Barthelemy': 'America/St_Barthelemy.ics',
  'America/St Barthelemy': 'America/St_Barthelemy.ics',
  'America/St_Johns': 'America/St_Johns.ics',
  'America/St Johns': 'America/St_Johns.ics',
  'America/St_Kitts': 'America/St_Kitts.ics',
  'America/St Kitts': 'America/St_Kitts.ics',
  'America/St_Lucia': 'America/St_Lucia.ics',
  'America/St Lucia': 'America/St_Lucia.ics',
  'America/St_Thomas': 'America/St_Thomas.ics',
  'America/St Thomas': 'America/St_Thomas.ics',
  'America/St_Vincent': 'America/St_Vincent.ics',
  'America/St Vincent': 'America/St_Vincent.ics',
  'America/Swift_Current': 'America/Swift_Current.ics',
  'America/Swift Current': 'America/Swift_Current.ics',
  'America/Tegucigalpa': 'America/Tegucigalpa.ics',
  'America/Thule': 'America/Thule.ics',
  'America/Thunder_Bay': 'America/Thunder_Bay.ics',
  'America/Thunder Bay': 'America/Thunder_Bay.ics',
  'America/Tijuana': 'America/Tijuana.ics',
  'America/Toronto': 'America/Toronto.ics',
  'America/Tortola': 'America/Tortola.ics',
  'America/Vancouver': 'America/Vancouver.ics',
  'America/Whitehorse': 'America/Whitehorse.ics',
  'America/Winnipeg': 'America/Winnipeg.ics',
  'America/Yakutat': 'America/Yakutat.ics',
  'America/Yellowknife': 'America/Yellowknife.ics',
  'Antarctica/Casey': 'Antarctica/Casey.ics',
  'Antarctica/Davis': 'Antarctica/Davis.ics',
  'Antarctica/DumontDUrville': 'Antarctica/DumontDUrville.ics',
  'Antarctica/Macquarie': 'Antarctica/Macquarie.ics',
  'Antarctica/Mawson': 'Antarctica/Mawson.ics',
  'Antarctica/McMurdo': 'Antarctica/McMurdo.ics',
  'Antarctica/Palmer': 'Antarctica/Palmer.ics',
  'Antarctica/Rothera': 'Antarctica/Rothera.ics',
  'Antarctica/Syowa': 'Antarctica/Syowa.ics',
  'Antarctica/Troll': 'Antarctica/Troll.ics',
  'Antarctica/Vostok': 'Antarctica/Vostok.ics',
  'Arctic/Longyearbyen': 'Arctic/Longyearbyen.ics',
  'Asia/Aden': 'Asia/Aden.ics',
  'Asia/Almaty': 'Asia/Almaty.ics',
  'Asia/Amman': 'Asia/Amman.ics',
  'Asia/Anadyr': 'Asia/Anadyr.ics',
  'Asia/Aqtau': 'Asia/Aqtau.ics',
  'Asia/Aqtobe': 'Asia/Aqtobe.ics',
  'Asia/Ashgabat': 'Asia/Ashgabat.ics',
  'Asia/Atyrau': 'Asia/Atyrau.ics',
  'Asia/Baghdad': 'Asia/Baghdad.ics',
  'Asia/Bahrain': 'Asia/Bahrain.ics',
  'Asia/Baku': 'Asia/Baku.ics',
  'Asia/Bangkok': 'Asia/Bangkok.ics',
  'Asia/Barnaul': 'Asia/Barnaul.ics',
  'Asia/Beirut': 'Asia/Beirut.ics',
  'Asia/Bishkek': 'Asia/Bishkek.ics',
  'Asia/Brunei': 'Asia/Brunei.ics',
  'Asia/Chita': 'Asia/Chita.ics',
  'Asia/Choibalsan': 'Asia/Choibalsan.ics',
  'Asia/Colombo': 'Asia/Colombo.ics',
  'Asia/Damascus': 'Asia/Damascus.ics',
  'Asia/Dhaka': 'Asia/Dhaka.ics',
  'Asia/Dili': 'Asia/Dili.ics',
  'Asia/Dubai': 'Asia/Dubai.ics',
  'Asia/Dushanbe': 'Asia/Dushanbe.ics',
  'Asia/Famagusta': 'Asia/Famagusta.ics',
  'Asia/Gaza': 'Asia/Gaza.ics',
  'Asia/Hebron': 'Asia/Hebron.ics',
  'Asia/Ho_Chi_Minh': 'Asia/Ho_Chi_Minh.ics',
  'Asia/Ho Chi_Minh': 'Asia/Ho_Chi_Minh.ics',
  'Asia/Hong_Kong': 'Asia/Hong_Kong.ics',
  'Asia/Hong Kong': 'Asia/Hong_Kong.ics',
  'Asia/Hovd': 'Asia/Hovd.ics',
  'Asia/Irkutsk': 'Asia/Irkutsk.ics',
  'Asia/Istanbul': 'Asia/Istanbul.ics',
  'Asia/Jakarta': 'Asia/Jakarta.ics',
  'Asia/Jayapura': 'Asia/Jayapura.ics',
  'Asia/Jerusalem': 'Asia/Jerusalem.ics',
  'Asia/Kabul': 'Asia/Kabul.ics',
  'Asia/Kamchatka': 'Asia/Kamchatka.ics',
  'Asia/Karachi': 'Asia/Karachi.ics',
  'Asia/Kathmandu': 'Asia/Kathmandu.ics',
  'Asia/Khandyga': 'Asia/Khandyga.ics',
  'Asia/Kolkata': 'Asia/Kolkata.ics',
  'Asia/Krasnoyarsk': 'Asia/Krasnoyarsk.ics',
  'Asia/Kuala_Lumpur': 'Asia/Kuala_Lumpur.ics',
  'Asia/Kuala Lumpur': 'Asia/Kuala_Lumpur.ics',
  'Asia/Kuching': 'Asia/Kuching.ics',
  'Asia/Kuwait': 'Asia/Kuwait.ics',
  'Asia/Macau': 'Asia/Macau.ics',
  'Asia/Magadan': 'Asia/Magadan.ics',
  'Asia/Makassar': 'Asia/Makassar.ics',
  'Asia/Manila': 'Asia/Manila.ics',
  'Asia/Muscat': 'Asia/Muscat.ics',
  'Asia/Nicosia': 'Asia/Nicosia.ics',
  'Asia/Novokuznetsk': 'Asia/Novokuznetsk.ics',
  'Asia/Novosibirsk': 'Asia/Novosibirsk.ics',
  'Asia/Omsk': 'Asia/Omsk.ics',
  'Asia/Oral': 'Asia/Oral.ics',
  'Asia/Phnom_Penh': 'Asia/Phnom_Penh.ics',
  'Asia/Phnom Penh': 'Asia/Phnom_Penh.ics',
  'Asia/Pontianak': 'Asia/Pontianak.ics',
  'Asia/Pyongyang': 'Asia/Pyongyang.ics',
  'Asia/Qatar': 'Asia/Qatar.ics',
  'Asia/Qyzylorda': 'Asia/Qyzylorda.ics',
  'Asia/Riyadh': 'Asia/Riyadh.ics',
  'Asia/Sakhalin': 'Asia/Sakhalin.ics',
  'Asia/Samarkand': 'Asia/Samarkand.ics',
  'Asia/Seoul': 'Asia/Seoul.ics',
  'Asia/Shanghai': 'Asia/Shanghai.ics',
  'Asia/Singapore': 'Asia/Singapore.ics',
  'Asia/Srednekolymsk': 'Asia/Srednekolymsk.ics',
  'Asia/Taipei': 'Asia/Taipei.ics',
  'Asia/Tashkent': 'Asia/Tashkent.ics',
  'Asia/Tbilisi': 'Asia/Tbilisi.ics',
  'Asia/Tehran': 'Asia/Tehran.ics',
  'Asia/Thimphu': 'Asia/Thimphu.ics',
  'Asia/Tokyo': 'Asia/Tokyo.ics',
  'Asia/Tomsk': 'Asia/Tomsk.ics',
  'Asia/Ulaanbaatar': 'Asia/Ulaanbaatar.ics',
  'Asia/Urumqi': 'Asia/Urumqi.ics',
  'Asia/Ust-Nera': 'Asia/Ust-Nera.ics',
  'Asia/Vientiane': 'Asia/Vientiane.ics',
  'Asia/Vladivostok': 'Asia/Vladivostok.ics',
  'Asia/Yakutsk': 'Asia/Yakutsk.ics',
  'Asia/Yangon': 'Asia/Yangon.ics',
  'Asia/Yekaterinburg': 'Asia/Yekaterinburg.ics',
  'Asia/Yerevan': 'Asia/Yerevan.ics',
  'Atlantic/Azores': 'Atlantic/Azores.ics',
  'Atlantic/Bermuda': 'Atlantic/Bermuda.ics',
  'Atlantic/Canary': 'Atlantic/Canary.ics',
  'Atlantic/Cape_Verde': 'Atlantic/Cape_Verde.ics',
  'Atlantic/Cape Verde': 'Atlantic/Cape_Verde.ics',
  'Atlantic/Faroe': 'Atlantic/Faroe.ics',
  'Atlantic/Madeira': 'Atlantic/Madeira.ics',
  'Atlantic/Reykjavik': 'Atlantic/Reykjavik.ics',
  'Atlantic/South_Georgia': 'Atlantic/South_Georgia.ics',
  'Atlantic/South Georgia': 'Atlantic/South_Georgia.ics',
  'Atlantic/St_Helena': 'Atlantic/St_Helena.ics',
  'Atlantic/St Helena': 'Atlantic/St_Helena.ics',
  'Atlantic/Stanley': 'Atlantic/Stanley.ics',
  'Australia/Adelaide': 'Australia/Adelaide.ics',
  'Australia/Brisbane': 'Australia/Brisbane.ics',
  'Australia/Broken_Hill': 'Australia/Broken_Hill.ics',
  'Australia/Broken Hill': 'Australia/Broken_Hill.ics',
  'Australia/Currie': 'Australia/Currie.ics',
  'Australia/Darwin': 'Australia/Darwin.ics',
  'Australia/Eucla': 'Australia/Eucla.ics',
  'Australia/Hobart': 'Australia/Hobart.ics',
  'Australia/Lindeman': 'Australia/Lindeman.ics',
  'Australia/Lord_Howe': 'Australia/Lord_Howe.ics',
  'Australia/Lord Howe': 'Australia/Lord_Howe.ics',
  'Australia/Melbourne': 'Australia/Melbourne.ics',
  'Australia/Perth': 'Australia/Perth.ics',
  'Australia/Sydney': 'Australia/Sydney.ics',
  'Australian Central Standard Time': 'Australian Central Standard Time.ics',
  'Etc/GMT-0': 'Etc/GMT-0.ics',
  'GMT-0': 'Etc/GMT-0.ics',
  'Etc/GMT-1': 'Etc/GMT-1.ics',
  'GMT-1': 'Etc/GMT-1.ics',
  'Etc/GMT-10': 'Etc/GMT-10.ics',
  'GMT-10': 'Etc/GMT-10.ics',
  'Etc/GMT-11': 'Etc/GMT-11.ics',
  'GMT-11': 'Etc/GMT-11.ics',
  'Etc/GMT-12': 'Etc/GMT-12.ics',
  'GMT-12': 'Etc/GMT-12.ics',
  'Etc/GMT-2': 'Etc/GMT-2.ics',
  'GMT-2': 'Etc/GMT-2.ics',
  'Etc/GMT-3': 'Etc/GMT-3.ics',
  'GMT-3': 'Etc/GMT-3.ics',
  'Etc/GMT-4': 'Etc/GMT-4.ics',
  'GMT-4': 'Etc/GMT-4.ics',
  'Etc/GMT-5': 'Etc/GMT-5.ics',
  'GMT-5': 'Etc/GMT-5.ics',
  'Etc/GMT-6': 'Etc/GMT-6.ics',
  'GMT-6': 'Etc/GMT-6.ics',
  'Etc/GMT-7': 'Etc/GMT-7.ics',
  'GMT-7': 'Etc/GMT-7.ics',
  'Etc/GMT-8': 'Etc/GMT-8.ics',
  'GMT-8': 'Etc/GMT-8.ics',
  'Etc/GMT-9': 'Etc/GMT-9.ics',
  'GMT-9': 'Etc/GMT-9.ics',
  'Etc/GMT': 'Etc/GMT.ics',
  GMT: 'Etc/GMT.ics',
  'Etc/GMT+0': 'Etc/GMT+0.ics',
  'GMT+0': 'Etc/GMT+0.ics',
  'Etc/GMT+1': 'Etc/GMT+1.ics',
  'GMT+1': 'Etc/GMT+1.ics',
  'Etc/GMT+10': 'Etc/GMT+10.ics',
  'GMT+10': 'Etc/GMT+10.ics',
  'Etc/GMT+11': 'Etc/GMT+11.ics',
  'GMT+11': 'Etc/GMT+11.ics',
  'Etc/GMT+12': 'Etc/GMT+12.ics',
  'GMT+12': 'Etc/GMT+12.ics',
  'Etc/GMT+13': 'Etc/GMT+13.ics',
  'GMT+13': 'Etc/GMT+13.ics',
  'Etc/GMT+14': 'Etc/GMT+14.ics',
  'GMT+14': 'Etc/GMT+14.ics',
  'Etc/GMT+2': 'Etc/GMT+2.ics',
  'GMT+2': 'Etc/GMT+2.ics',
  'Etc/GMT+3': 'Etc/GMT+3.ics',
  'GMT+3': 'Etc/GMT+3.ics',
  'Etc/GMT+4': 'Etc/GMT+4.ics',
  'GMT+4': 'Etc/GMT+4.ics',
  'Etc/GMT+5': 'Etc/GMT+5.ics',
  'GMT+5': 'Etc/GMT+5.ics',
  'Etc/GMT+6': 'Etc/GMT+6.ics',
  'GMT+6': 'Etc/GMT+6.ics',
  'Etc/GMT+7': 'Etc/GMT+7.ics',
  'GMT+7': 'Etc/GMT+7.ics',
  'Etc/GMT+8': 'Etc/GMT+8.ics',
  'GMT+8': 'Etc/GMT+8.ics',
  'Etc/GMT+9': 'Etc/GMT+9.ics',
  'GMT+9': 'Etc/GMT+9.ics',
  'Etc/GMT0': 'Etc/GMT0.ics',
  GMT0: 'Etc/GMT0.ics',
  'Etc/Greenwich': 'Etc/Greenwich.ics',
  Greenwich: 'Etc/Greenwich.ics',
  'Etc/UCT': 'Etc/UCT.ics',
  UCT: 'Etc/UCT.ics',
  'Etc/Universal': 'Etc/Universal.ics',
  Universal: 'Etc/Universal.ics',
  'Etc/UTC': 'Etc/UTC.ics',
  UTC: 'Etc/UTC.ics',
  'Etc/Zulu': 'Etc/Zulu.ics',
  Zulu: 'Etc/Zulu.ics',
  'Europe/Amsterdam': 'Europe/Amsterdam.ics',
  'Europe/Andorra': 'Europe/Andorra.ics',
  'Europe/Astrakhan': 'Europe/Astrakhan.ics',
  'Europe/Athens': 'Europe/Athens.ics',
  'Europe/Belgrade': 'Europe/Belgrade.ics',
  'Europe/Berlin': 'Europe/Berlin.ics',
  'Europe/Bratislava': 'Europe/Bratislava.ics',
  'Europe/Brussels': 'Europe/Brussels.ics',
  'Europe/Bucharest': 'Europe/Bucharest.ics',
  'Europe/Budapest': 'Europe/Budapest.ics',
  'Europe/Busingen': 'Europe/Busingen.ics',
  'Europe/Chisinau': 'Europe/Chisinau.ics',
  'Europe/Copenhagen': 'Europe/Copenhagen.ics',
  'Europe/Dublin': 'Europe/Dublin.ics',
  'Europe/Gibraltar': 'Europe/Gibraltar.ics',
  'Europe/Guernsey': 'Europe/Guernsey.ics',
  'Europe/Helsinki': 'Europe/Helsinki.ics',
  'Europe/Isle_of_Man': 'Europe/Isle_of_Man.ics',
  'Europe/Isle of_Man': 'Europe/Isle_of_Man.ics',
  'Europe/Istanbul': 'Europe/Istanbul.ics',
  'Europe/Jersey': 'Europe/Jersey.ics',
  'Europe/Kaliningrad': 'Europe/Kaliningrad.ics',
  'Europe/Kiev': 'Europe/Kiev.ics',
  'Europe/Kirov': 'Europe/Kirov.ics',
  'Europe/Lisbon': 'Europe/Lisbon.ics',
  'Europe/Ljubljana': 'Europe/Ljubljana.ics',
  'Europe/London': 'Europe/London.ics',
  'Europe/Luxembourg': 'Europe/Luxembourg.ics',
  'Europe/Madrid': 'Europe/Madrid.ics',
  'Europe/Malta': 'Europe/Malta.ics',
  'Europe/Mariehamn': 'Europe/Mariehamn.ics',
  'Europe/Minsk': 'Europe/Minsk.ics',
  'Europe/Monaco': 'Europe/Monaco.ics',
  'Europe/Moscow': 'Europe/Moscow.ics',
  'Europe/Nicosia': 'Europe/Nicosia.ics',
  'Europe/Oslo': 'Europe/Oslo.ics',
  'Europe/Paris': 'Europe/Paris.ics',
  'Europe/Podgorica': 'Europe/Podgorica.ics',
  'Europe/Prague': 'Europe/Prague.ics',
  'Europe/Riga': 'Europe/Riga.ics',
  'Europe/Rome': 'Europe/Rome.ics',
  'Europe/Samara': 'Europe/Samara.ics',
  'Europe/San_Marino': 'Europe/San_Marino.ics',
  'Europe/San Marino': 'Europe/San_Marino.ics',
  'Europe/Sarajevo': 'Europe/Sarajevo.ics',
  'Europe/Saratov': 'Europe/Saratov.ics',
  'Europe/Simferopol': 'Europe/Simferopol.ics',
  'Europe/Skopje': 'Europe/Skopje.ics',
  'Europe/Sofia': 'Europe/Sofia.ics',
  'Europe/Stockholm': 'Europe/Stockholm.ics',
  'Europe/Tallinn': 'Europe/Tallinn.ics',
  'Europe/Tirane': 'Europe/Tirane.ics',
  'Europe/Ulyanovsk': 'Europe/Ulyanovsk.ics',
  'Europe/Uzhgorod': 'Europe/Uzhgorod.ics',
  'Europe/Vaduz': 'Europe/Vaduz.ics',
  'Europe/Vatican': 'Europe/Vatican.ics',
  'Europe/Vienna': 'Europe/Vienna.ics',
  'Europe/Vilnius': 'Europe/Vilnius.ics',
  'Europe/Volgograd': 'Europe/Volgograd.ics',
  'Europe/Warsaw': 'Europe/Warsaw.ics',
  'Europe/Zagreb': 'Europe/Zagreb.ics',
  'Europe/Zaporozhye': 'Europe/Zaporozhye.ics',
  'Europe/Zurich': 'Europe/Zurich.ics',
  'India Standard Time': 'India Standard Time.ics',
  'Indian/Antananarivo': 'Indian/Antananarivo.ics',
  'Indian/Chagos': 'Indian/Chagos.ics',
  'Indian/Christmas': 'Indian/Christmas.ics',
  'Indian/Cocos': 'Indian/Cocos.ics',
  'Indian/Comoro': 'Indian/Comoro.ics',
  'Indian/Kerguelen': 'Indian/Kerguelen.ics',
  'Indian/Mahe': 'Indian/Mahe.ics',
  'Indian/Maldives': 'Indian/Maldives.ics',
  'Indian/Mauritius': 'Indian/Mauritius.ics',
  'Indian/Mayotte': 'Indian/Mayotte.ics',
  'Indian/Reunion': 'Indian/Reunion.ics',
  'Myanmar Time': 'Myanmar Time.ics',
  'Nepal Time': 'Nepal Time.ics',
  'Newfoundland Standard Time': 'Newfoundland Standard Time.ics',
  'Pacific/Apia': 'Pacific/Apia.ics',
  'Pacific/Auckland': 'Pacific/Auckland.ics',
  'Pacific/Bougainville': 'Pacific/Bougainville.ics',
  'Pacific/Chatham': 'Pacific/Chatham.ics',
  'Pacific/Chuuk': 'Pacific/Chuuk.ics',
  'Pacific/Easter': 'Pacific/Easter.ics',
  'Pacific/Efate': 'Pacific/Efate.ics',
  'Pacific/Enderbury': 'Pacific/Enderbury.ics',
  'Pacific/Fakaofo': 'Pacific/Fakaofo.ics',
  'Pacific/Fiji': 'Pacific/Fiji.ics',
  'Pacific/Funafuti': 'Pacific/Funafuti.ics',
  'Pacific/Galapagos': 'Pacific/Galapagos.ics',
  'Pacific/Gambier': 'Pacific/Gambier.ics',
  'Pacific/Guadalcanal': 'Pacific/Guadalcanal.ics',
  'Pacific/Guam': 'Pacific/Guam.ics',
  'Pacific/Honolulu': 'Pacific/Honolulu.ics',
  'Pacific/Kiritimati': 'Pacific/Kiritimati.ics',
  'Pacific/Kosrae': 'Pacific/Kosrae.ics',
  'Pacific/Kwajalein': 'Pacific/Kwajalein.ics',
  'Pacific/Majuro': 'Pacific/Majuro.ics',
  'Pacific/Marquesas': 'Pacific/Marquesas.ics',
  'Pacific/Midway': 'Pacific/Midway.ics',
  'Pacific/Nauru': 'Pacific/Nauru.ics',
  'Pacific/Niue': 'Pacific/Niue.ics',
  'Pacific/Norfolk': 'Pacific/Norfolk.ics',
  'Pacific/Noumea': 'Pacific/Noumea.ics',
  'Pacific/Pago_Pago': 'Pacific/Pago_Pago.ics',
  'Pacific/Pago Pago': 'Pacific/Pago_Pago.ics',
  'Pacific/Palau': 'Pacific/Palau.ics',
  'Pacific/Pitcairn': 'Pacific/Pitcairn.ics',
  'Pacific/Pohnpei': 'Pacific/Pohnpei.ics',
  'Pacific/Port_Moresby': 'Pacific/Port_Moresby.ics',
  'Pacific/Port Moresby': 'Pacific/Port_Moresby.ics',
  'Pacific/Rarotonga': 'Pacific/Rarotonga.ics',
  'Pacific/Saipan': 'Pacific/Saipan.ics',
  'Pacific/Tahiti': 'Pacific/Tahiti.ics',
  'Pacific/Tarawa': 'Pacific/Tarawa.ics',
  'Pacific/Tongatapu': 'Pacific/Tongatapu.ics',
  'Pacific/Wake': 'Pacific/Wake.ics',
  'Pacific/Wallis': 'Pacific/Wallis.ics',
  'Venezuela Standard Time': 'Venezuela Standard Time.ics',
  'Dateline Standard Time': 'Etc/GMT-12.ics',
  'Samoa Standard Time': 'Etc/GMT-11.ics',
  'Hawaiian Standard Time': 'Etc/GMT-10.ics',
  'Alaskan Standard Time': 'Etc/GMT-9.ics',
  'Pacific Standard Time': 'Etc/GMT-8.ics',
  'Mountain Standard Time': 'Etc/GMT-7.ics',
  'Mexico Standard Time 2': 'Etc/GMT-7.ics',
  'US Mountain Standard Time': 'Etc/GMT-7.ics',
  'Central Standard Time': 'Etc/GMT-6.ics',
  'Canada Central Standard Time': 'Etc/GMT-6.ics',
  'Mexico Standard Time': 'Etc/GMT-6.ics',
  'Central America Standard Time': 'Etc/GMT-6.ics',
  'Eastern Standard Time': 'Etc/GMT-5.ics',
  'US Eastern Standard Time': 'Etc/GMT-5.ics',
  'SA Pacific Standard Time': 'Etc/GMT-5.ics',
  'Atlantic Standard Time': 'Etc/GMT-4.ics',
  'SA Western Standard Time': 'Etc/GMT-4.ics',
  'Pacific SA Standard Time': 'Etc/GMT-4.ics',
  'E South America Standard Time': 'Etc/GMT-3.ics',
  'SA Eastern Standard Time': 'Etc/GMT-3.ics',
  'Greenland Standard Time': 'Etc/GMT-3.ics',
  'Mid-Atlantic Standard Time': 'Etc/GMT-2.ics',
  'Azores Standard Time': 'Etc/GMT-1.ics',
  'Cape Verde Standard Time': 'Etc/GMT-1.ics',
  'GMT Standard Time': 'Etc/GMT.ics',
  'Greenwich Standard Time': 'Etc/Greenwich.ics',
  'Central Europe Standard Time': 'Etc/GMT+1.ics',
  'Central European Standard Time': 'Etc/GMT+1.ics',
  'Romance Standard Time': 'Etc/GMT+1.ics',
  'W Europe Standard Time': 'Etc/GMT+1.ics',
  'W Central Africa Standard Time': 'Etc/GMT+1.ics',
  'E Europe Standard Time': 'Etc/GMT+2.ics',
  'Egypt Standard Time': 'Etc/GMT+2.ics',
  'FLE Standard Time': 'Etc/GMT+2.ics',
  'GTB Standard Time': 'Etc/GMT+2.ics',
  'Israel Standard Time': 'Etc/GMT+2.ics',
  'South Africa Standard Time': 'Etc/GMT+2.ics',
  'Russian Standard Time': 'Etc/GMT+3.ics',
  'Arab Standard Time': 'Etc/GMT+3.ics',
  'E Africa Standard Time': 'Etc/GMT+3.ics',
  'Arabic Standard Time': 'Etc/GMT+3.ics',
  'Iran Standard Time': 'Etc/GMT+4.ics',
  'Arabian Standard Time': 'Etc/GMT+4.ics',
  'Caucasus Standard Time': 'Etc/GMT+4.ics',
  'Ekaterinburg Standard Time': 'Etc/GMT+5.ics',
  'West Asia Standard Time': 'Etc/GMT+5.ics',
  'Central Asia Standard Time': 'Etc/GMT+6.ics',
  'Sri Lanka Standard Time': 'Etc/GMT+6.ics',
  'N Central Asia Standard Time': 'Etc/GMT+6.ics',
  'Myanmar Standard Time': 'Myanmar Time.ics',
  'SE Asia Standard Time': 'Etc/GMT+7.ics',
  'North Asia Standard Time': 'Etc/GMT+7.ics',
  'China Standard Time': 'Etc/GMT+8.ics',
  'Singapore Standard Time': 'Etc/GMT+8.ics',
  'Taipei Standard Time': 'Etc/GMT+8.ics',
  'W Australia Standard Time': 'Etc/GMT+8.ics',
  'North Asia East Standard Time': 'Etc/GMT+8.ics',
  'Korea Standard Time': 'Etc/GMT+9.ics',
  'Tokyo Standard Time': 'Etc/GMT+9.ics',
  'Yakutsk Standard Time': 'Etc/GMT+9.ics',
  'AUS Central Standard Time': 'Australian Central Standard Time.ics',
  'Cen Australia Standard Time': 'Australian Central Standard Time.ics',
  'AUS Eastern Standard Time': 'Etc/GMT+10.ics',
  'E Australia Standard Time': 'Etc/GMT+10.ics',
  'Tasmania Standard Time': 'Etc/GMT+10.ics',
  'Vladivostok Standard Time': 'Etc/GMT+10.ics',
  'West Pacific Standard Time': 'Etc/GMT+10.ics',
  'Central Pacific Standard Time': 'Etc/GMT+11.ics',
  'Fiji Islands Standard Time': 'Etc/GMT+12.ics',
  'New Zealand Standard Time': 'Etc/GMT+12.ics',
  'Tonga Standard Time': 'Etc/GMT+13.ics',
  'Asia/Calcutta': 'Asia/Kolkata.ics',
  'Asia/Katmandu': 'Nepal Time.ics',
  'Asia/Rangoon': 'Asia/Yangon.ics',
  'America/Buenos Aires': 'America/Argentina/Buenos_Aires.ics',
  'Canada/Atlantic': 'America/Aruba.ics',
  'Canada/Newfoundland': 'Newfoundland Standard Time.ics',
  'Canada/Saskatchewan': 'undefined',
  'US/Eastern': 'America/New_York.ics',
  'US/Central': 'America/Chicago.ics',
  'US/Mountain': 'America/Denver.ics',
  'US/Pacific': 'America/Los_Angeles.ics',
  'US/Arizona': 'America/Phoenix.ics',
  'US/East-Indiana': 'America/Halifax.ics',
  ET: 'America/New_York.ics',
  CT: 'America/Chicago.ics',
  MT: 'America/Denver.ics',
  PT: 'America/Los_Angeles.ics',
  AK: 'America/Anchorage.ics',
  HAST: 'Pacific/Honolulu.ics',
  MST: 'America/Phoenix.ics',
  AST: 'America/Aruba.ics',
  MOST: 'Africa/Casablanca.ics',
  GST: 'Africa/Casablanca.ics',
  WET: 'Europe/Amsterdam.ics',
  CET: 'Europe/Belgrade.ics',
  RST: 'Europe/Copenhagen.ics',
  CEST: 'Europe/Sarajevo.ics',
  ECT: 'Africa/Douala.ics',
  JST: 'Europe/Bucharest.ics',
  GTBST: 'Europe/Bucharest.ics',
  MEST: 'Africa/Cairo.ics',
  EGST: 'Africa/Cairo.ics',
  SST: 'Africa/Cairo.ics',
  SAST: 'Africa/Harare.ics',
  EET: 'Europe/Helsinki.ics',
  ISST: 'Asia/Jerusalem.ics',
  EEST: 'Asia/Jerusalem.ics',
  NMST: 'Asia/Jerusalem.ics',
  ARST: 'Asia/Baghdad.ics',
  ABST: 'Asia/Kuwait.ics',
  MSK: 'Europe/Moscow.ics',
  EAT: 'Asia/Kuwait.ics',
  IRST: 'Asia/Tehran.ics',
  ARBST: 'Asia/Muscat.ics',
  AZT: 'Asia/Baku.ics',
  MUT: 'Asia/Baku.ics',
  GET: 'Asia/Baku.ics',
  AMT: 'Asia/Baku.ics',
  AFT: 'Asia/Baku.ics',
  YEKT: 'Asia/Yekaterinburg.ics',
  PKT: 'Asia/Karachi.ics',
  WAST: 'Asia/Yekaterinburg.ics',
  IST: 'Asia/Kolkata.ics',
  SLT: 'Asia/Kolkata.ics',
  NPT: 'Nepal Time.ics',
  BTT: 'Asia/Dhaka.ics',
  BST: 'Asia/Dhaka.ics',
  NCAST: 'Asia/Dhaka.ics',
  MYST: 'Asia/Yangon.ics',
  THA: 'Asia/Yangon.ics',
  KRAT: 'Asia/Yangon.ics',
  IRKT: 'Asia/Irkutsk.ics',
  SNST: 'Asia/Taipei.ics',
  AWST: 'Australia/Perth.ics',
  TIST: 'Asia/Taipei.ics',
  UST: 'Asia/Taipei.ics',
  TST: 'Asia/Tokyo.ics',
  KST: 'Asia/Seoul.ics',
  YAKT: 'Asia/Yakutsk.ics',
  CAUST: 'Australia/Adelaide.ics',
  ACST: 'Australia/Darwin.ics',
  EAST: 'Australia/Brisbane.ics',
  AEST: 'Australia/Sydney.ics',
  WPST: 'Pacific/Guam.ics',
  TAST: 'Australia/Hobart.ics',
  VLAT: 'Asia/Vladivostok.ics',
  SBT: 'Pacific/Guadalcanal.ics',
  NZST: 'Pacific/Auckland.ics',
  UTC12: 'Etc/GMT-12.ics',
  FJT: 'Pacific/Fiji.ics',
  PETT: 'Etc/GMT+12.ics',
  PHOT: 'Pacific/Tongatapu.ics',
  AZOST: 'Atlantic/Azores.ics',
  CVT: 'Atlantic/Cape_Verde.ics',
  ESAST: 'America/Sao_Paulo.ics',
  ART: 'America/Argentina/Buenos_Aires.ics',
  SAEST: 'Etc/GMT-3.ics',
  GNST: 'America/Godthab.ics',
  MVST: 'America/Montevideo.ics',
  NST: 'Newfoundland Standard Time.ics',
  PRST: 'America/Aruba.ics',
  CBST: 'America/Aruba.ics',
  SAWST: 'America/Santiago.ics',
  PSAST: 'America/Santiago.ics',
  VST: 'America/Caracas.ics',
  SAPST: 'America/Bogota.ics',
  EST: 'America/Halifax.ics',
  CAST: 'America/Mexico_City.ics',
  CST: 'America/Mexico_City.ics',
  CCST: 'undefined',
  MSTM: 'America/Mazatlan.ics',
  PST: 'America/Los_Angeles.ics',
  SMST: 'Pacific/Midway.ics',
  BIT: 'Etc/GMT+12.ics'
};
